services:
  - type: web
    name: virtualtrade
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 