services:
  - type: web
    name: virtualtrade
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: PYTHONMALLOC
        value: debug
      - key: PYTHONMALLOCSTATS
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONHASHSEED
        value: "0"
      - key: PYTHONIOENCODING
        value: "utf-8"
    autoDeploy: true
    branch: main 